version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
      # - type: bind
      #   source: ./modules/testModule # local path to the module
      #   target: /var/www/html/modules/testModule # path to be mounted in the container
      # - type: bind
      #   source: ./themes/myTheme # local path to the theme
      #   target:  /var/www/html/themes/myTheme # path to be mounted in the container
      # - psdata:/var/www/html
      - ./img:/var/www/html/img
      - ./template:/var/www/html/template
      - ./themes:/var/www/html/themes

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      networks:
        - prestashop_network
      environment:
        PMA_HOST: some-mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - 8081:80

networks:
  prestashop_network:

volumes:
  psdata:
  dbdata: